"""add_extended_vps_plan_configuration

Revision ID: 2913f7156710
Revises: 557028f598c7
Create Date: 2026-01-15 19:59:28.301297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '2913f7156710'
down_revision = '557028f598c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ip_groups')
    op.drop_index('ix_compose_templates_id', table_name='compose_templates')
    op.drop_table('compose_templates')
    op.drop_table('cloud_init_profiles')
    op.drop_table('vps_plans')
    op.drop_index('ix_metric_history_id', table_name='metric_history')
    op.drop_index('ix_metric_history_node_id', table_name='metric_history')
    op.drop_index('ix_metric_history_resource_id', table_name='metric_history')
    op.drop_index('ix_metric_history_resource_type', table_name='metric_history')
    op.drop_index('ix_metric_history_timeframe', table_name='metric_history')
    op.drop_index('ix_metric_history_timestamp', table_name='metric_history')
    op.drop_table('metric_history')
    op.drop_table('vm_requests')
    op.drop_table('user_cloud_licenses')
    op.drop_table('cloud_license_plans')
    op.drop_table('recipes')
    op.drop_table('iso_groups')
    op.drop_index('ix_firewall_rules_id', table_name='firewall_rules')
    op.drop_index('ix_firewall_rules_node_id', table_name='firewall_rules')
    op.drop_index('ix_firewall_rules_vmid', table_name='firewall_rules')
    op.drop_table('firewall_rules')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_index('ix_notifications_id', table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('action_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), nullable=False),
    sa.Column('read_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_id', 'notifications', ['id'], unique=False)
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_table('firewall_rules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vmid', sa.INTEGER(), nullable=False),
    sa.Column('node_id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('protocol', sa.VARCHAR(), nullable=True),
    sa.Column('source', sa.VARCHAR(), nullable=True),
    sa.Column('dest', sa.VARCHAR(), nullable=True),
    sa.Column('sport', sa.VARCHAR(), nullable=True),
    sa.Column('dport', sa.VARCHAR(), nullable=True),
    sa.Column('iface', sa.VARCHAR(), nullable=True),
    sa.Column('comment', sa.VARCHAR(), nullable=True),
    sa.Column('log', sa.VARCHAR(), nullable=True),
    sa.Column('macro', sa.VARCHAR(), nullable=True),
    sa.Column('pos', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by_user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['proxmox_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_firewall_rules_vmid', 'firewall_rules', ['vmid'], unique=False)
    op.create_index('ix_firewall_rules_node_id', 'firewall_rules', ['node_id'], unique=False)
    op.create_index('ix_firewall_rules_id', 'firewall_rules', ['id'], unique=False)
    op.create_table('iso_groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recipes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cloud_license_plans',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('max_vms', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('max_cpu_cores', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('max_ram_mb', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('max_disk_gb', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('max_snapshots', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('max_backups', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('max_isos', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('max_ips', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('allow_self_approval', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_cloud_licenses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('plan_id', sa.INTEGER(), nullable=False),
    sa.Column('overrides_json', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vm_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('node_id', sa.INTEGER(), nullable=True),
    sa.Column('plan_id', sa.INTEGER(), nullable=False),
    sa.Column('cloud_init_profile_id', sa.INTEGER(), nullable=True),
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('notes', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('auto_approve', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('approved_at', sa.DATETIME(), nullable=True),
    sa.Column('fulfilled_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('resource_type', sa.VARCHAR(), nullable=False),
    sa.Column('resource_id', sa.VARCHAR(), nullable=False),
    sa.Column('node_id', sa.INTEGER(), nullable=True),
    sa.Column('timeframe', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('cpu_usage', sa.FLOAT(), nullable=True),
    sa.Column('cpu_iowait', sa.FLOAT(), nullable=True),
    sa.Column('memory_used', sa.FLOAT(), nullable=True),
    sa.Column('memory_total', sa.FLOAT(), nullable=True),
    sa.Column('memory_usage_percent', sa.FLOAT(), nullable=True),
    sa.Column('disk_read_bytes', sa.FLOAT(), nullable=True),
    sa.Column('disk_write_bytes', sa.FLOAT(), nullable=True),
    sa.Column('disk_used', sa.FLOAT(), nullable=True),
    sa.Column('disk_total', sa.FLOAT(), nullable=True),
    sa.Column('network_in_bytes', sa.FLOAT(), nullable=True),
    sa.Column('network_out_bytes', sa.FLOAT(), nullable=True),
    sa.Column('storage_used', sa.FLOAT(), nullable=True),
    sa.Column('storage_total', sa.FLOAT(), nullable=True),
    sa.Column('storage_usage_percent', sa.FLOAT(), nullable=True),
    sa.Column('additional_metrics', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['proxmox_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metric_history_timestamp', 'metric_history', ['timestamp'], unique=False)
    op.create_index('ix_metric_history_timeframe', 'metric_history', ['timeframe'], unique=False)
    op.create_index('ix_metric_history_resource_type', 'metric_history', ['resource_type'], unique=False)
    op.create_index('ix_metric_history_resource_id', 'metric_history', ['resource_id'], unique=False)
    op.create_index('ix_metric_history_node_id', 'metric_history', ['node_id'], unique=False)
    op.create_index('ix_metric_history_id', 'metric_history', ['id'], unique=False)
    op.create_table('vps_plans',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('cpu_cores', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('ram_mb', sa.INTEGER(), server_default=sa.text("'512'"), nullable=False),
    sa.Column('disk_gb', sa.INTEGER(), server_default=sa.text("'10'"), nullable=False),
    sa.Column('virtio', sa.BOOLEAN(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('scsi', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('enable_vnc', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('ip_group_id', sa.INTEGER(), nullable=True),
    sa.Column('iso_group_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cloud_init_profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('metadata', sa.TEXT(), nullable=True),
    sa.Column('default_user', sa.VARCHAR(length=255), nullable=True),
    sa.Column('default_password', sa.VARCHAR(length=255), nullable=True),
    sa.Column('disable_root', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('apt_update', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('apt_upgrade', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('apt_reboot_if_required', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('packages', sqlite.JSON(), nullable=True),
    sa.Column('package_update_frequency', sa.VARCHAR(length=50), nullable=True),
    sa.Column('bootcmd', sqlite.JSON(), nullable=True),
    sa.Column('runcmd', sqlite.JSON(), nullable=True),
    sa.Column('cron_jobs', sqlite.JSON(), nullable=True),
    sa.Column('write_files', sqlite.JSON(), nullable=True),
    sa.Column('install_docker', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('docker_compose_content', sa.TEXT(), nullable=True),
    sa.Column('docker_compose_path', sa.VARCHAR(length=512), server_default=sa.text("'/root/docker-compose.yml'"), nullable=True),
    sa.Column('start_docker_compose', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('network_config_template', sa.TEXT(), nullable=True),
    sa.Column('hostname_template', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ssh_authorized_keys', sqlite.JSON(), nullable=True),
    sa.Column('ssh_pwauth', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=64), nullable=True),
    sa.Column('locale', sa.VARCHAR(length=64), nullable=True),
    sa.Column('custom_cloud_config', sa.TEXT(), nullable=True),
    sa.Column('available_variables', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('compose_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('variables', sa.TEXT(), nullable=True),
    sa.Column('auto_update', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_compose_templates_id', 'compose_templates', ['id'], unique=False)
    op.create_table('ip_groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('ip_pool_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
